### ISSUE TITLE
Legacy plugin warning on server startup

### ISSUE THREAD

**Issue by a1375625918** [Kr1S-D/UltimateAntibotRecoded#19]
It seems that Spigot plugin requires an api-version value in plugin.yml.

```
[12:31:27] [Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[12:31:30] [Server thread/WARN]: Legacy plugin UltimateAntiBot v4.0.5-ABYSS does not specify an api-version.
```

There was one but removed at https://github.com/Kr1S-D/UltimateAntibotRecoded/commit/0eff339e8d689650138ec792981846188bbf185e#diff-b5c292a3385267124f6e34442c90396184a819b51775eec5785f7b7280e71b90L4 . Wondering why.

**Comment by Kr1S-D** [comment]
It blocked the execution of the plugin in 1.13 1.14 and 1.15, so I decided to remove it, however that message shouldn't affect the server in terms of performance

**Comment by a1375625918** [comment]
A 1.13 value should work. Or I just safely ignore the warning.



---- Replied Message ----
| From | ***@***.***> |
| Date | 02/01/2023 08:57 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [Kr1S-D/UltimateAntibotRecoded] Legacy plugin warning on server startup (Issue #19) |

It blocked the execution of the plugin in 1.13 1.14 and 1.15, so I decided to remove it, however that message shouldn't affect the server in terms of performance

**Comment by Kr1S-D** [comment]
Yes, first I didn't know how to make it work and I removed it, I found it later but I forgot to change it in the code, it will be added in the next push before the official release

**Comment by Kr1S-D** [comment]
fixed

**Comment by a1375625918** [comment]
I'm sorry to hear that this issue is closed as invalid without any explanation. I tried the most recent BetterRTP version 3.6.8-2 but the problem persists. Logs are available at https://pastebin.com/7wJB3JG8 . ChunkLogger is a simple piece of code that listens to ChunkLoadEvent and prints a line to console when `event.isNewChunk()==true` . Please let me know if you need more information about this. 
---- Replied Message ----
| From | ***@***.***> |
| Date | 04/27/2023 05:40 |
| To | RonanPlugins/BetterRTP ***@***.***> |
| Cc | a1375625918 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [RonanPlugins/BetterRTP] BetterRTP loads lots of chunks (Issue #127) |

Closed #127 as not planned.
